"""add followup payment confirmation

Revision ID: 20260305_add_followup_payment
Revises: c6725f8775d1
Create Date: 2026-03-05 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '20260305_add_followup_payment'
down_revision: Union[str, Sequence[str], None] = 'c6725f8775d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add payment confirmation fields to follow_up table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_up', sa.Column('payment_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('follow_up', sa.Column('payment_confirmed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove payment confirmation fields from follow_up table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_up', 'payment_confirmed_date')
    op.drop_column('follow_up', 'payment_confirmed')
    # ### end Alembic commands ###
