"""initial schema

Revision ID: 46da6b8459ca
Revises: 
Create Date: 2026-01-02 19:00:46.244334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46da6b8459ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_master',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('kingdom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('common_indicators', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key_symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modalities', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperament', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('miasmatic_background', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('repertory_rubrics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_master_name'), 'medicine_master', ['name'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'STAFF', 'ADMIN', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('clinic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('clinic_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('doctor_medicine_stock',
    sa.Column('potency', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('potency_scale', sa.Enum('X', 'C', 'LM', 'Q', 'M', 'CM', 'MM', name='potencyscale'), nullable=False),
    sa.Column('form', sa.Enum('PILLS', 'GLOBULES', 'DROPS', 'POWDER', 'OINTMENT', 'SUPPOSITORY', 'INJECTION', name='medicineform'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('low_stock_threshold', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_medicine_stock_doctor_id'), 'doctor_medicine_stock', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_medicine_stock_medicine_id'), 'doctor_medicine_stock', ['medicine_id'], unique=False)
    op.create_table('patient',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'CHILD', name='patientgender'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('referred_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('medical_history', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drug_allergies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('family_history', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('last_visit_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_doctor_id'), 'patient', ['doctor_id'], unique=False)
    op.create_table('appointment',
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('consultation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointment_datetime', 'appointment', ['appointment_date', 'appointment_time'], unique=False)
    op.create_index('idx_doctor_appointments', 'appointment', ['doctor_id', 'appointment_date', 'status'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_table('patient_case',
    sa.Column('chief_complaint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('onset', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sensation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modalities', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concomitants', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mentals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physicals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('miasm_assessment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vitality_assessment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('case_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('case_date', sa.Date(), nullable=False),
    sa.Column('case_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_case_case_number'), 'patient_case', ['case_number'], unique=True)
    op.create_index(op.f('ix_patient_case_doctor_id'), 'patient_case', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_case_patient_id'), 'patient_case', ['patient_id'], unique=False)
    op.create_table('prescription',
    sa.Column('prescription_type', sa.Enum('ACUTE', 'CHRONIC', 'CONSTITUTIONAL', 'INTERCURRENT', 'NOSODE', 'SARCODE', 'TAUTODE', name='prescriptiontype'), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follow_up_advice', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dietary_restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avoidance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_date', sa.Date(), nullable=False),
    sa.Column('prescription_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_case.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_case_id'), 'prescription', ['case_id'], unique=False)
    op.create_index(op.f('ix_prescription_doctor_id'), 'prescription', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescription_prescription_number'), 'prescription', ['prescription_number'], unique=True)
    op.create_table('follow_up',
    sa.Column('subjective_improvement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('objective_findings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aggravation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amelioration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('general_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['patient_case.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_case_id'), 'follow_up', ['case_id'], unique=False)
    op.create_index(op.f('ix_follow_up_doctor_id'), 'follow_up', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_follow_up_prescription_id'), 'follow_up', ['prescription_id'], unique=False)
    op.create_table('medicine_usage_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stock_item_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('used_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['doctor_medicine_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_by_date', 'medicine_usage_log', ['used_date'], unique=False)
    op.create_index(op.f('ix_medicine_usage_log_patient_id'), 'medicine_usage_log', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medicine_usage_log_prescription_id'), 'medicine_usage_log', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_medicine_usage_log_stock_item_id'), 'medicine_usage_log', ['stock_item_id'], unique=False)
    op.create_table('prescription_medicine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('stock_used_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.ForeignKeyConstraint(['stock_used_id'], ['doctor_medicine_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_medicine_medicine_id'), 'prescription_medicine', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_prescription_medicine_prescription_id'), 'prescription_medicine', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_medicine_prescription_id'), table_name='prescription_medicine')
    op.drop_index(op.f('ix_prescription_medicine_medicine_id'), table_name='prescription_medicine')
    op.drop_table('prescription_medicine')
    op.drop_index(op.f('ix_medicine_usage_log_stock_item_id'), table_name='medicine_usage_log')
    op.drop_index(op.f('ix_medicine_usage_log_prescription_id'), table_name='medicine_usage_log')
    op.drop_index(op.f('ix_medicine_usage_log_patient_id'), table_name='medicine_usage_log')
    op.drop_index('idx_usage_by_date', table_name='medicine_usage_log')
    op.drop_table('medicine_usage_log')
    op.drop_index(op.f('ix_follow_up_prescription_id'), table_name='follow_up')
    op.drop_index(op.f('ix_follow_up_doctor_id'), table_name='follow_up')
    op.drop_index(op.f('ix_follow_up_case_id'), table_name='follow_up')
    op.drop_table('follow_up')
    op.drop_index(op.f('ix_prescription_prescription_number'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_doctor_id'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_case_id'), table_name='prescription')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_patient_case_patient_id'), table_name='patient_case')
    op.drop_index(op.f('ix_patient_case_doctor_id'), table_name='patient_case')
    op.drop_index(op.f('ix_patient_case_case_number'), table_name='patient_case')
    op.drop_table('patient_case')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index('idx_doctor_appointments', table_name='appointment')
    op.drop_index('idx_appointment_datetime', table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_patient_doctor_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_medicine_stock_medicine_id'), table_name='doctor_medicine_stock')
    op.drop_index(op.f('ix_doctor_medicine_stock_doctor_id'), table_name='doctor_medicine_stock')
    op.drop_table('doctor_medicine_stock')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_medicine_master_name'), table_name='medicine_master')
    op.drop_table('medicine_master')
    # ### end Alembic commands ###
