"""fix_case_prescription_relationships

Revision ID: 4dd790bf463d
Revises: a03a1a20c2a4
Create Date: 2026-02-21 16:16:48.420821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4dd790bf463d'
down_revision: Union[str, Sequence[str], None] = 'a03a1a20c2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status columns with server-side defaults for existing rows
    op.add_column('follow_up', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='scheduled'))
    op.add_column('patient_case', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='open'))
    op.add_column('prescription', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='open'))
    
    # Alter gender column from ENUM to string
    op.alter_column('patient', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'CHILD', name='patientgender'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    
    # Alter prescription_type from ENUM to string
    op.alter_column('prescription', 'prescription_type',
               existing_type=postgresql.ENUM('ACUTE', 'CHRONIC', 'CONSTITUTIONAL', 'INTERCURRENT', 'NOSODE', 'SARCODE', 'TAUTODE', name='prescriptiontype'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    
    # Add frequency column to prescription_medicine (nullable)
    op.add_column('prescription_medicine', sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription_medicine', 'frequency')
    op.alter_column('prescription', 'prescription_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=postgresql.ENUM('ACUTE', 'CHRONIC', 'CONSTITUTIONAL', 'INTERCURRENT', 'NOSODE', 'SARCODE', 'TAUTODE', name='prescriptiontype'),
               existing_nullable=False)
    op.drop_column('prescription', 'status')
    op.drop_column('patient_case', 'status')
    op.alter_column('patient', 'gender',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'CHILD', name='patientgender'),
               existing_nullable=False)
    op.drop_column('follow_up', 'status')
    # ### end Alembic commands ###
