"""appointment relation improved

Revision ID: 7547ef73538d
Revises: db9d44a2cfde
Create Date: 2026-01-18 09:09:14.773966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7547ef73538d'
down_revision: Union[str, Sequence[str], None] = 'db9d44a2cfde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_case', sa.Column('appointment_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_patient_case_appointment_id'), 'patient_case', ['appointment_id'], unique=False)
    op.create_foreign_key(None, 'patient_case', 'appointment', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_case', type_='foreignkey')
    op.drop_index(op.f('ix_patient_case_appointment_id'), table_name='patient_case')
    op.drop_column('patient_case', 'appointment_id')
    # ### end Alembic commands ###
