"""patient booking and login

Revision ID: 89e09060d5ff
Revises: a37e14dd73ae
Create Date: 2026-01-24 14:43:35.268008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '89e09060d5ff'
down_revision: Union[str, Sequence[str], None] = 'a37e14dd73ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_case_field_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'field_name', name='uq_doctor_field')
    )
    op.create_index(op.f('ix_doctor_case_field_preference_doctor_id'), 'doctor_case_field_preference', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_case_field_preference_field_name'), 'doctor_case_field_preference', ['field_name'], unique=False)
    op.add_column('patient', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('last_login', sa.Date(), nullable=True))
    op.add_column('patient_case', sa.Column('chief_complaint_patient', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('patient_case', sa.Column('noted_complaint_doctor', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('patient_case', sa.Column('peculiar_symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient_case', sa.Column('causation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient_case', sa.Column('lab_reports', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient_case', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('patient_case', 'miasm_assessment')
    op.drop_column('patient_case', 'concomitants')
    op.drop_column('patient_case', 'chief_complaint')
    op.drop_column('patient_case', 'location')
    op.drop_column('patient_case', 'generals')
    op.drop_column('patient_case', 'vitality_assessment')
    op.drop_column('patient_case', 'case_notes')
    op.drop_column('patient_case', 'modalities')
    op.drop_column('patient_case', 'mentals')
    op.drop_column('patient_case', 'sensation')
    op.drop_column('patient_case', 'onset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_case', sa.Column('onset', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('sensation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('mentals', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('modalities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('case_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('vitality_assessment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('generals', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('chief_complaint', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('patient_case', sa.Column('concomitants', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_case', sa.Column('miasm_assessment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient_case', 'custom_fields')
    op.drop_column('patient_case', 'lab_reports')
    op.drop_column('patient_case', 'causation')
    op.drop_column('patient_case', 'peculiar_symptoms')
    op.drop_column('patient_case', 'noted_complaint_doctor')
    op.drop_column('patient_case', 'chief_complaint_patient')
    op.drop_column('patient', 'last_login')
    op.drop_column('patient', 'hashed_password')
    op.drop_index(op.f('ix_doctor_case_field_preference_field_name'), table_name='doctor_case_field_preference')
    op.drop_index(op.f('ix_doctor_case_field_preference_doctor_id'), table_name='doctor_case_field_preference')
    op.drop_table('doctor_case_field_preference')
    # ### end Alembic commands ###
