"""enums

Revision ID: 98d4504f3022
Revises: d5da195ff0e5
Create Date: 2026-02-17 23:10:50.162567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '98d4504f3022'
down_revision: Union[str, Sequence[str], None] = 'd5da195ff0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update NULL values before adding NOT NULL constraints
    op.execute("UPDATE medicine SET potency = 'Unknown' WHERE potency IS NULL")
    op.execute("UPDATE medicine SET potency_scale = 'C' WHERE potency_scale IS NULL")
    op.execute("UPDATE medicine SET form = 'GLOBULES' WHERE form IS NULL")
    op.execute("UPDATE medicine SET is_verified = false WHERE is_verified IS NULL")
    op.execute("UPDATE medicine SET created_at = NOW() WHERE created_at IS NULL")
    
    op.alter_column('medicine', 'potency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('medicine', 'potency_scale',
               existing_type=postgresql.ENUM('C', 'X', 'Q', name='scaleenum'),
               nullable=False)
    op.alter_column('medicine', 'form',
               existing_type=postgresql.ENUM('DISKETTE', 'SOM', 'BLANKETS', 'BIO_CHEMIC', 'HOMOEO_TABS', 'GLOBULES', 'DILUTIONS', name='formenum'),
               nullable=False)
    op.alter_column('medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('medicine', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    
    # Fix prescriptiontype enum - change column to VARCHAR temporarily, drop old enum, create new one, change column back
    # Step 1: Change prescription_type column to VARCHAR
    op.alter_column('prescription', 'prescription_type',
                   existing_type=postgresql.ENUM('ACUTE', 'CHRONIC', 'CONSTITUTIONAL', 'INTERCURRENT', 'NOSODE', 'SARCODE', 'TAUTODE', name='prescriptiontype'),
                   type_=sa.VARCHAR(50),
                   postgresql_using="prescription_type::text")
    
    # Step 2: Drop old enum type
    op.execute("DROP TYPE prescriptiontype CASCADE")
    
    # Step 3: Create new enum type with correct values
    new_prescriptiontype = postgresql.ENUM(
        'Constitutional', 'Classical', 'Inter Current', 
        'Pure Bio Chemic', 'Mother Tincture', 'Patent',
        name='prescriptiontype'
    )
    new_prescriptiontype.create(bind, checkfirst=True)
    
    # Step 4: Change column back to new enum
    op.alter_column('prescription', 'prescription_type',
                   existing_type=sa.VARCHAR(50),
                   type_=new_prescriptiontype,
                   postgresql_using="prescription_type::prescriptiontype")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Change prescription_type column to VARCHAR
    op.alter_column('prescription', 'prescription_type',
                   existing_type=postgresql.ENUM('Constitutional', 'Classical', 'Inter Current', 'Pure Bio Chemic', 'Mother Tincture', 'Patent', name='prescriptiontype'),
                   type_=sa.VARCHAR(50),
                   postgresql_using="prescription_type::text")
    
    # Step 2: Drop new enum type
    op.execute("DROP TYPE prescriptiontype CASCADE")
    
    # Step 3: Create old enum type
    old_prescriptiontype = postgresql.ENUM(
        'ACUTE', 'CHRONIC', 'CONSTITUTIONAL', 'INTERCURRENT', 'NOSODE', 'SARCODE', 'TAUTODE',
        name='prescriptiontype'
    )
    old_prescriptiontype.create(bind, checkfirst=True)
    
    # Step 4: Change column back to old enum
    op.alter_column('prescription', 'prescription_type',
                   existing_type=sa.VARCHAR(50),
                   type_=old_prescriptiontype,
                   postgresql_using="CASE WHEN prescription_type = 'Constitutional' THEN 'CONSTITUTIONAL'::prescriptiontype ELSE 'ACUTE'::prescriptiontype END")
    
    op.alter_column('medicine', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('medicine', 'form',
               existing_type=postgresql.ENUM('DISKETTE', 'SOM', 'BLANKETS', 'BIO_CHEMIC', 'HOMOEO_TABS', 'GLOBULES', 'DILUTIONS', name='formenum'),
               nullable=True)
    op.alter_column('medicine', 'potency_scale',
               existing_type=postgresql.ENUM('C', 'X', 'Q', name='scaleenum'),
               nullable=True)
    op.alter_column('medicine', 'potency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
