"""dynamic enums

Revision ID: a03a1a20c2a4
Revises: 7db72229909d
Create Date: 2026-02-19 18:19:27.992274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a03a1a20c2a4'
down_revision: Union[str, Sequence[str], None] = '7db72229909d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_types',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enum_type_active', 'enum_types', ['is_active'], unique=False)
    op.create_index('idx_enum_type_key', 'enum_types', ['key'], unique=True)
    op.create_table('enum_options',
    sa.Column('enum_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enum_type_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enum_type_id'], ['enum_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enum_option_active', 'enum_options', ['is_active'], unique=False)
    op.create_index('idx_enum_option_sort', 'enum_options', ['enum_type_id', 'sort_order'], unique=False)
    op.create_index('idx_enum_option_type_id', 'enum_options', ['enum_type_id'], unique=False)
    op.create_index('idx_enum_option_type_value', 'enum_options', ['enum_type', 'value'], unique=False)
    op.create_index(op.f('ix_enum_options_enum_type_id'), 'enum_options', ['enum_type_id'], unique=False)
    op.create_table('doctor_enum_preferences',
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('enum_option_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enum_option_id'], ['enum_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doctor_enum_pref_doctor', 'doctor_enum_preferences', ['doctor_id'], unique=False)
    op.create_index('idx_doctor_enum_pref_doctor_option', 'doctor_enum_preferences', ['doctor_id', 'enum_option_id'], unique=True)
    op.create_index('idx_doctor_enum_pref_option', 'doctor_enum_preferences', ['enum_option_id'], unique=False)
    op.create_index(op.f('ix_doctor_enum_preferences_doctor_id'), 'doctor_enum_preferences', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_enum_preferences_enum_option_id'), 'doctor_enum_preferences', ['enum_option_id'], unique=False)
    op.alter_column('appointment', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_index(op.f('ix_doctor_medicine_preference_medicine_id'), 'doctor_medicine_preference', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_prescription_medicine_medicine_id'), 'prescription_medicine', ['medicine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_medicine_medicine_id'), table_name='prescription_medicine')
    op.drop_index(op.f('ix_doctor_medicine_preference_medicine_id'), table_name='doctor_medicine_preference')
    op.alter_column('appointment', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_doctor_enum_preferences_enum_option_id'), table_name='doctor_enum_preferences')
    op.drop_index(op.f('ix_doctor_enum_preferences_doctor_id'), table_name='doctor_enum_preferences')
    op.drop_index('idx_doctor_enum_pref_option', table_name='doctor_enum_preferences')
    op.drop_index('idx_doctor_enum_pref_doctor_option', table_name='doctor_enum_preferences')
    op.drop_index('idx_doctor_enum_pref_doctor', table_name='doctor_enum_preferences')
    op.drop_table('doctor_enum_preferences')
    op.drop_index(op.f('ix_enum_options_enum_type_id'), table_name='enum_options')
    op.drop_index('idx_enum_option_type_value', table_name='enum_options')
    op.drop_index('idx_enum_option_type_id', table_name='enum_options')
    op.drop_index('idx_enum_option_sort', table_name='enum_options')
    op.drop_index('idx_enum_option_active', table_name='enum_options')
    op.drop_table('enum_options')
    op.drop_index('idx_enum_type_key', table_name='enum_types')
    op.drop_index('idx_enum_type_active', table_name='enum_types')
    op.drop_table('enum_types')
    # ### end Alembic commands ###
