"""followup custom fields

Revision ID: c6725f8775d1
Revises: f8139387cdcd
Create Date: 2026-03-02 23:01:31.787981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c6725f8775d1'
down_revision: Union[str, Sequence[str], None] = 'f8139387cdcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_followup_field_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'field_name', name='uq_doctor_followup_field')
    )
    op.create_index(op.f('ix_doctor_followup_field_preference_doctor_id'), 'doctor_followup_field_preference', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_followup_field_preference_field_name'), 'doctor_followup_field_preference', ['field_name'], unique=False)
    op.add_column('follow_up', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_up', 'custom_fields')
    op.drop_index(op.f('ix_doctor_followup_field_preference_field_name'), table_name='doctor_followup_field_preference')
    op.drop_index(op.f('ix_doctor_followup_field_preference_doctor_id'), table_name='doctor_followup_field_preference')
    op.drop_table('doctor_followup_field_preference')
    # ### end Alembic commands ###
