"""Medicine and Prescriptions

Revision ID: d5da195ff0e5
Revises: 4085cd9f9281
Create Date: 2026-02-16 13:46:53.860644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd5da195ff0e5'
down_revision: Union[str, Sequence[str], None] = '4085cd9f9281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop constraints and dependent tables before dropping doctor_medicine_stock
    op.drop_constraint(op.f('prescription_medicine_stock_used_id_fkey'), 'prescription_medicine', type_='foreignkey')
    op.drop_column('prescription_medicine', 'stock_used_id')
    op.drop_column('prescription_medicine', 'quantity_used')
    op.drop_index(op.f('idx_usage_by_date'), table_name='medicine_usage_log')
    op.drop_index(op.f('ix_medicine_usage_log_patient_id'), table_name='medicine_usage_log')
    op.drop_index(op.f('ix_medicine_usage_log_prescription_id'), table_name='medicine_usage_log')
    op.drop_index(op.f('ix_medicine_usage_log_stock_item_id'), table_name='medicine_usage_log')
    op.drop_table('medicine_usage_log')
    op.drop_index(op.f('ix_doctor_medicine_stock_doctor_id'), table_name='doctor_medicine_stock')
    op.drop_index(op.f('ix_doctor_medicine_stock_medicine_id'), table_name='doctor_medicine_stock')
    op.drop_table('doctor_medicine_stock')
    
    # Now create new tables and columns
    op.create_table('doctor_medicine_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_medicine_preference_doctor_id'), 'doctor_medicine_preference', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_medicine_preference_medicine_id'), 'doctor_medicine_preference', ['medicine_id'], unique=False)
    op.add_column('medicine', sa.Column('potency', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('medicine', sa.Column('potency_scale', sa.Enum('C', 'X', 'Q', name='scaleenum'), nullable=True))
    op.add_column('medicine', sa.Column('form', sa.Enum('DISKETTE', 'SOM', 'BLANKETS', 'BIO_CHEMIC', 'HOMOEO_TABS', 'GLOBULES', 'DILUTIONS', name='formenum'), nullable=True))
    op.add_column('medicine', sa.Column('manufacturer', sa.Enum('SCHWABE', 'RECKWEG', 'LEMASAR', 'DOLISOS', 'KAMAL', 'MASOOD', 'BM', 'KENT', 'BROOKS', 'WARIS_SHAH', 'SELF_PACKING', name='manufacturerenum'), nullable=True))
    op.add_column('medicine', sa.Column('created_by_doctor_id', sa.Uuid(), nullable=True))
    op.add_column('medicine', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('medicine', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_medicine_created_by_doctor_id'), 'medicine', ['created_by_doctor_id'], unique=False)
    op.create_foreign_key(None, 'medicine', 'user', ['created_by_doctor_id'], ['id'])
    op.add_column('prescription_medicine', sa.Column('quantity_prescribed', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_medicine', sa.Column('quantity_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('prescription_medicine', sa.Column('stock_used_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('prescription_medicine_stock_used_id_fkey'), 'prescription_medicine', 'doctor_medicine_stock', ['stock_used_id'], ['id'])
    op.drop_column('prescription_medicine', 'quantity_prescribed')
    op.drop_constraint(None, 'medicine', type_='foreignkey')
    op.drop_index(op.f('ix_medicine_created_by_doctor_id'), table_name='medicine')
    op.drop_column('medicine', 'is_verified')
    op.drop_column('medicine', 'created_at')
    op.drop_column('medicine', 'created_by_doctor_id')
    op.drop_column('medicine', 'manufacturer')
    op.drop_column('medicine', 'form')
    op.drop_column('medicine', 'potency_scale')
    op.drop_column('medicine', 'potency')
    op.create_table('medicine_usage_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prescription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('used_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('medicine_usage_log_patient_id_fkey')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], name=op.f('medicine_usage_log_prescription_id_fkey')),
    sa.ForeignKeyConstraint(['stock_item_id'], ['doctor_medicine_stock.id'], name=op.f('medicine_usage_log_stock_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medicine_usage_log_pkey'))
    )
    op.create_index(op.f('ix_medicine_usage_log_stock_item_id'), 'medicine_usage_log', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_medicine_usage_log_prescription_id'), 'medicine_usage_log', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_medicine_usage_log_patient_id'), 'medicine_usage_log', ['patient_id'], unique=False)
    op.create_index(op.f('idx_usage_by_date'), 'medicine_usage_log', ['used_date'], unique=False)
    op.create_table('doctor_medicine_stock',
    sa.Column('potency', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('potency_scale', postgresql.ENUM('C', 'X', 'Q', name='scaleenum'), autoincrement=False, nullable=False),
    sa.Column('form', postgresql.ENUM('DISKETTE', 'SOM', 'BLANKETS', 'BIO_CHEMIC', 'HOMOEO_TABS', 'GLOBULES', 'DILUTIONS', name='formenum'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', postgresql.ENUM('SCHWABE', 'RECKWEG', 'LEMASAR', 'DOLISOS', 'KAMAL', 'MASOOD', 'BM', 'KENT', 'BROOKS', 'WARIS_SHAH', 'SELF_PACKING', name='manufacturerenum'), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_used_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('low_stock_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], name=op.f('doctor_medicine_stock_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], name=op.f('doctor_medicine_stock_medicine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_medicine_stock_pkey'))
    )
    op.create_index(op.f('ix_doctor_medicine_stock_medicine_id'), 'doctor_medicine_stock', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_doctor_medicine_stock_doctor_id'), 'doctor_medicine_stock', ['doctor_id'], unique=False)
    op.drop_index(op.f('ix_doctor_medicine_preference_medicine_id'), table_name='doctor_medicine_preference')
    op.drop_index(op.f('ix_doctor_medicine_preference_doctor_id'), table_name='doctor_medicine_preference')
    op.drop_table('doctor_medicine_preference')
    # ### end Alembic commands ###
