"""user profile and doctor approval from admin

Revision ID: d89e53a0cd12
Revises: 20260125_appt_unique
Create Date: 2026-02-06 00:12:18.423885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd89e53a0cd12'
down_revision: Union[str, Sequence[str], None] = '20260125_appt_unique'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_appointment_no_double_booking'), table_name='appointment')
    
    # FIX: Handle NULL values in chief_complaint_patient before making it NOT NULL
    op.execute("UPDATE patient_case SET chief_complaint_patient = '' WHERE chief_complaint_patient IS NULL")
    
    op.alter_column('patient_case', 'chief_complaint_patient',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.add_column('user', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_approved')
    op.alter_column('patient_case', 'chief_complaint_patient',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_index(op.f('idx_appointment_no_double_booking'), 'appointment', ['doctor_id', 'appointment_date', 'appointment_time'], unique=True)
    # ### end Alembic commands ###
