"""finance setup

Revision ID: f8139387cdcd
Revises: 20260222_add_duration_days
Create Date: 2026-02-28 16:45:10.765388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f8139387cdcd'
down_revision: Union[str, Sequence[str], None] = '20260222_add_duration_days'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_cash_book',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_cash_book_doctor_id'), 'finance_cash_book', ['doctor_id'], unique=False)
    op.create_table('finance_cash_book_custom_field',
    sa.Column('field_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cash_book_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cash_book_id'], ['finance_cash_book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_book_id', 'field_key', name='uq_cash_book_custom_field_key')
    )
    op.create_index('idx_cash_book_custom_field_display_order', 'finance_cash_book_custom_field', ['cash_book_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_finance_cash_book_custom_field_cash_book_id'), 'finance_cash_book_custom_field', ['cash_book_id'], unique=False)
    op.create_table('finance_transaction',
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('cash_book_id', sa.Uuid(), nullable=False),
    sa.Column('nature_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cash_book_id'], ['finance_cash_book.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_category_code', 'finance_transaction', ['category_code'], unique=False)
    op.create_index('idx_transaction_date', 'finance_transaction', ['cash_book_id', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_deleted', 'finance_transaction', ['is_deleted'], unique=False)
    op.create_index('idx_transaction_nature_code', 'finance_transaction', ['nature_code'], unique=False)
    op.create_index(op.f('ix_finance_transaction_cash_book_id'), 'finance_transaction', ['cash_book_id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_doctor_id'), 'finance_transaction', ['doctor_id'], unique=False)
    op.create_table('finance_transaction_custom_field_value',
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['finance_cash_book_custom_field.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'field_id', name='uq_transaction_custom_field_value')
    )
    op.create_index(op.f('ix_finance_transaction_custom_field_value_field_id'), 'finance_transaction_custom_field_value', ['field_id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_custom_field_value_transaction_id'), 'finance_transaction_custom_field_value', ['transaction_id'], unique=False)
    op.alter_column('medicine', 'potency_scale',
               existing_type=postgresql.ENUM('C', 'X', 'Q', name='scaleenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.alter_column('medicine', 'form',
               existing_type=postgresql.ENUM('DISKETTE', 'SOM', 'BLANKETS', 'BIO_CHEMIC', 'HOMOEO_TABS', 'GLOBULES', 'DILUTIONS', name='formenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('medicine', 'manufacturer',
               existing_type=postgresql.ENUM('SCHWABE', 'RECKWEG', 'LEMASAR', 'DOLISOS', 'KAMAL', 'MASOOD', 'BM', 'KENT', 'BROOKS', 'WARIS_SHAH', 'SELF_PACKING', name='manufacturerenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=True)
    op.alter_column('prescription', 'duration_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Integer version of prescription_duration for auto follow-up date calculation',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescription', 'duration_days',
               existing_type=sa.INTEGER(),
               comment='Integer version of prescription_duration for auto follow-up date calculation',
               existing_nullable=True)
    op.alter_column('medicine', 'manufacturer',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=postgresql.ENUM('SCHWABE', 'RECKWEG', 'LEMASAR', 'DOLISOS', 'KAMAL', 'MASOOD', 'BM', 'KENT', 'BROOKS', 'WARIS_SHAH', 'SELF_PACKING', name='manufacturerenum'),
               existing_nullable=True)
    op.alter_column('medicine', 'form',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=postgresql.ENUM('DISKETTE', 'SOM', 'BLANKETS', 'BIO_CHEMIC', 'HOMOEO_TABS', 'GLOBULES', 'DILUTIONS', name='formenum'),
               existing_nullable=False)
    op.alter_column('medicine', 'potency_scale',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=postgresql.ENUM('C', 'X', 'Q', name='scaleenum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_finance_transaction_custom_field_value_transaction_id'), table_name='finance_transaction_custom_field_value')
    op.drop_index(op.f('ix_finance_transaction_custom_field_value_field_id'), table_name='finance_transaction_custom_field_value')
    op.drop_table('finance_transaction_custom_field_value')
    op.drop_index(op.f('ix_finance_transaction_doctor_id'), table_name='finance_transaction')
    op.drop_index(op.f('ix_finance_transaction_cash_book_id'), table_name='finance_transaction')
    op.drop_index('idx_transaction_nature_code', table_name='finance_transaction')
    op.drop_index('idx_transaction_deleted', table_name='finance_transaction')
    op.drop_index('idx_transaction_date', table_name='finance_transaction')
    op.drop_index('idx_transaction_category_code', table_name='finance_transaction')
    op.drop_table('finance_transaction')
    op.drop_index(op.f('ix_finance_cash_book_custom_field_cash_book_id'), table_name='finance_cash_book_custom_field')
    op.drop_index('idx_cash_book_custom_field_display_order', table_name='finance_cash_book_custom_field')
    op.drop_table('finance_cash_book_custom_field')
    op.drop_index(op.f('ix_finance_cash_book_doctor_id'), table_name='finance_cash_book')
    op.drop_table('finance_cash_book')
    # ### end Alembic commands ###
