"""medicne

Revision ID: fd14529643fb
Revises: ccaec4e11a58
Create Date: 2026-02-13 17:38:55.304825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd14529643fb'
down_revision: Union[str, Sequence[str], None] = 'ccaec4e11a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop foreign key constraints
    op.drop_constraint('doctor_medicine_stock_medicine_id_fkey', 'doctor_medicine_stock', type_='foreignkey')
    op.drop_constraint('prescription_medicine_medicine_id_fkey', 'prescription_medicine', type_='foreignkey')
    
    # Make medicine_id columns nullable to allow conversion
    op.alter_column('doctor_medicine_stock', 'medicine_id',
               existing_type=sa.UUID(),
               existing_nullable=False,
               nullable=True)
    op.alter_column('prescription_medicine', 'medicine_id',
               existing_type=sa.UUID(),
               existing_nullable=False,
               nullable=True)
    
    # Convert medicine_id columns from UUID to Integer
    op.alter_column('doctor_medicine_stock', 'medicine_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='NULL::INTEGER')
    op.alter_column('prescription_medicine', 'medicine_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='NULL::INTEGER')
    
    # Create new medicine table (simplified version of medicine_master)
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_name'), 'medicine', ['name'], unique=False)
    
    # Drop old table and its index
    op.drop_index(op.f('ix_medicine_master_name'), table_name='medicine_master')
    op.drop_table('medicine_master')
    
    # Recreate foreign key constraints pointing to new medicine table (now nullable during transition)
    op.create_foreign_key('doctor_medicine_stock_medicine_id_fkey', 'doctor_medicine_stock', 'medicine', ['medicine_id'], ['id'])
    op.create_foreign_key('prescription_medicine_medicine_id_fkey', 'prescription_medicine', 'medicine', ['medicine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints
    op.drop_constraint('prescription_medicine_medicine_id_fkey', 'prescription_medicine', type_='foreignkey')
    op.drop_constraint('doctor_medicine_stock_medicine_id_fkey', 'doctor_medicine_stock', type_='foreignkey')
    
    # Drop new medicine table
    op.drop_index(op.f('ix_medicine_name'), table_name='medicine')
    op.drop_table('medicine')
    
    # Recreate old medicine_master table
    op.create_table('medicine_master',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('kingdom', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('common_indicators', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key_symptoms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modalities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('temperament', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('miasmatic_background', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repertory_rubrics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='medicine_master_pkey')
    )
    op.create_index(op.f('ix_medicine_master_name'), 'medicine_master', ['name'], unique=False)
    
    # Convert medicine_id columns back from Integer to UUID (will be nullable)
    op.alter_column('prescription_medicine', 'medicine_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('doctor_medicine_stock', 'medicine_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    
    # Make columns NOT NULL again (if they were before)
    op.alter_column('prescription_medicine', 'medicine_id',
               existing_nullable=True,
               nullable=False)
    op.alter_column('doctor_medicine_stock', 'medicine_id',
               existing_nullable=True,
               nullable=False)
    
    # Recreate foreign key constraints to old table
    op.create_foreign_key('prescription_medicine_medicine_id_fkey', 'prescription_medicine', 'medicine_master', ['medicine_id'], ['id'])
    op.create_foreign_key('doctor_medicine_stock_medicine_id_fkey', 'doctor_medicine_stock', 'medicine_master', ['medicine_id'], ['id'])
    # ### end Alembic commands ###
